### ISSUE TITLE
Masterpass

### ISSUE THREAD

**Issue by ErshovYS** [Mastercard/oauth1-signer-go#1]
I use this library to signing requests for Masterpass, but I did some changes in code (sha1 and encoding).  
How can I push my branch for review?

**Comment by Akshaykdubey** [comment]
Hi @ErshovYS ,
Thanks for raising the issue and willing to contribute to the code.
Please raise a Pull Request(PR) with a detailed description as to what changes you are proposing, how it will improve the code and how it will be useful as a developer.
We will review the code and merge it once approved.

Thanks!

**Comment by ErshovYS** [comment]
To create Pull Request, I must choose different branches, but when I push my branch, I see the message:  
```
ERROR: Permission to Mastercard/oauth1-signer-go.git denied to ErshovYS.
fatal: Could not read from remote repository.
```

**Comment by ErshovYS** [comment]
Ok, I create new repository for this issue - https://github.com/ErshovYS/masterpass-oauth1-signer-go

**Comment by Akshaykdubey** [comment]
Did you try forking this repository and then making changes to the forked repo?
You can then create a PR from the forked repo.
The repo you created: https://github.com/ErshovYS/masterpass-oauth1-signer-go is not a forked repo.

Follow below docs:
Doc to fork a repo: https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo
Doc to create PR from a forked repo: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by ErshovYS** [comment]
Oh, sorry - https://github.com/Mastercard/oauth1-signer-go/pull/2
