### ISSUE TITLE
[REQ] Handle URL paths without leading slash

### ISSUE THREAD

**Issue by dacohen** [Mastercard/oauth1-signer-go#13]
### Is your feature request related to a problem? Please describe.

When constructing a `net.URL`, sometimes the `Path` member does not have a leading slash. This is common when using the `JoinPath` function, for example.

```
u, _ := url.Parse("https://api.mastercard.com")
serviceUrl := u.JoinPath("/test/service")
fmt.Println(serviceUrl.Path) // test/service
fmt.Println(serviceUrl.String()) // https://api.mastercard.com/test/service
```

However, the `getBaseUrlString` in this package doesn't correctly join the host and path
```
u, _ := url.Parse("https://api.mastercard.com")
serviceUrl := u.JoinPath("/test/service")
baseUrl := getBaseUrlString(serviceUrl)
fmt.Println(baseUrl) // https://api.mastercard.comtest/service
```

### Describe the solution you'd like

The `getBaseUrlString` function should correctly handle Paths with no leading slash. I've created an MR linked to this issue that addresses this.

**Comment by karen-avetisyan-mc** [comment]
Thanks for fixing it, release in v1.2.3
