### ISSUE TITLE
Signer not using latest request body

### ISSUE THREAD

**Issue by kaischwanke** [Mastercard/oauth1-signer-go#7]
#### Bug Report Checklist

- [x] Have you provided a code sample to reproduce the issue?
- [x] Have you tested with the latest release to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

**Unit test to reproduce the issue:**
```go
func TestMiddlewareIssue(t *testing.T) {
	originalBody := "{\"foo\": \"bar\"}"
	getRequest, _ := http.NewRequest("GET", "", strings.NewReader(originalBody))
	// second request, same body as the first one
	getRequestModified, _ := http.NewRequest("GET", "", strings.NewReader(originalBody))
	// faking a middleware function, which alters the request body (i.e. encrypting it)
	getRequestModified.Body = io.NopCloser(bytes.NewReader([]byte("{\"foo\": \"baz\"}")))
	bodyHash := getSignedBodyHash(getRequest)
	bodyHashModified := getSignedBodyHash(getRequestModified)
	// we would expect the oauth_body_hash values to be different, since both request have different payloads
	if bodyHash == bodyHashModified {
		t.Errorf("The oauth_body_hash should be different, since the request bodies were different")
	}
}

func getSignedBodyHash(r *http.Request) string {
	signer := &oauth.Signer{ConsumerKey: consumerKey, SigningKey: signingKey}
	_ = signer.Sign(r)
	authHeader := r.Header["Authorization"][0]
	return extractBodyHash(authHeader)
}

func extractBodyHash(input string) string {
	regexPattern := `oauth_body_hash="([^"]+)"`
	re := regexp.MustCompile(regexPattern)

	match := re.FindStringSubmatch(input)
	if len(match) == 0 {
		panic("value not found")
	}
	return match[1]
}
```

**Description**
The signing function on occasion might be using an outdated payload

**To Reproduce**
Create a http request, change the request body. The sign function will not use the updated body

**Expected behavior**
The latest version of the request body should be used

**Additional context**
This happens because of the way the `http.request getBody` function works. It will keep a snapshot of the initially created request.
https://github.com/golang/go/blob/master/src/net/http/request.go#L913

**Suggest a fix/enhancement**
PR created: https://github.com/Mastercard/oauth1-signer-go/pull/6

**Comment by danny-gallagher** [comment]
Resolved in: https://github.com/Mastercard/oauth1-signer-go/pull/8
