### ISSUE TITLE
Request body empty after reading it

### ISSUE THREAD

**Issue by kaischwanke** [Mastercard/oauth1-signer-go#9]
#### Bug Report Checklist

- [x] Have you provided a code sample to reproduce the issue?
- [x] Have you tested with the latest release to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

**Description**
Reading the request body in the sign function leaves it empty

**To Reproduce**
Test to illustrate the behaviour:
```golang
func TestBodyRestore(t *testing.T) {
	originalBody := "{\"foo\": \"bar\"}"
	getRequest, _ := http.NewRequest("GET", "", strings.NewReader(originalBody))
	bodyHash := getSignedBodyHash(getRequest)
	bodyHash2 := getSignedBodyHash(getRequest)
	if bodyHash != bodyHash2 {
		t.Errorf("Body hashes sould be the same")
	}
}

func getSignedBodyHash(r *http.Request) string {
	signer := &oauth.Signer{ConsumerKey: consumerKey, SigningKey: signingKey}
	_ = signer.Sign(r)
	authHeader := r.Header["Authorization"][0]
	return extractBodyHash(authHeader)
}

func extractBodyHash(input string) string {
	regexPattern := `oauth_body_hash="([^"]+)"`
	re := regexp.MustCompile(regexPattern)

	match := re.FindStringSubmatch(input)
	if len(match) == 0 {
		panic("value not found")
	}
	return match[1]
}
```
**Expected behavior**
The request body should remain intact after reading it

**Additional context**
The request body in Go is a `ReadCloser` interface. Once you read the content, the buffer will be empty. 
I had forgotten about that behaviour in my previous PR

**Related issues/PRs**
PR #10 created

**Comment by danny-gallagher** [comment]
Resolved in https://github.com/Mastercard/oauth1-signer-go/pull/10
